title: Stageverslag
description: Het stageverslag van Guus Groenink
url: 


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
  -
    scope: 
      path: "_projects" # an empty string here means all files in the project
    values:
      layout: "projects"
      permalink: :title/


collections:
  projects:
    output: true 