title: Pelgrim Portfolio
description: De portfolio van Joppe Pelgrim
url: /pelgrim_portfolio/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
